import 'dart:convert';
import 'dart:io';

void main() {
  final seeds = List<_ScenarioSeed>.generate(20, (index) {
    final sequence = index + 1;
    final number = sequence.toString().padLeft(2, '0');
    return _ScenarioSeed(
      id: 'synthetic_$number',
      name: 'Synthetic scenario $number',
      category: 'synthetic-$number',
      tag: 'fixture',
      background: 'Synthetic content for testing structured result creation.',
      details:
          'Synthetic second phase for testing multi-turn result persistence.',
      event1Title: 'Synthetic event $number-A',
      event1At: _fixtureAt(sequence, 9),
      event2Title: 'Synthetic event $number-B',
      event2At: _fixtureAt(sequence, 14),
      todoTitle: 'Synthetic task $number',
      todoDue: _fixtureAt(sequence, 18),
      knowledge1Title: 'Synthetic knowledge $number-A',
      knowledge1Body: 'Synthetic knowledge body with no personal data.',
      knowledge2Title: 'Synthetic knowledge $number-B',
      knowledge2Body: 'Synthetic second knowledge body with no personal data.',
    );
  });
  if (seeds.length != 20) {
    throw StateError('Expected 20 scenario seeds, got ${seeds.length}');
  }
  final scenarios = <Map<String, Object?>>[];
  for (var index = 0; index < seeds.length; index++) {
    scenarios.add(_scenario(seeds[index], index + 1));
  }

  final output = const JsonEncoder.withIndent('  ').convert({
    'version': 1,
    'generatedAt': '2026-10-05T23:00:00+08:00',
    'scenarios': scenarios,
  });
  final jsonFile = File('test/fixtures/large_scenario_20_cases.json');
  jsonFile.parent.createSync(recursive: true);
  jsonFile.writeAsStringSync('$output\n');

  final dartFile = File('test/large_scenario_20_cases.g.dart');
  dartFile.writeAsStringSync(
    '// Generated by tool/generate_large_scenarios.dart.\n'
    'const largeScenarioMaps = <Map<String, Object?>>'
    '${const JsonEncoder.withIndent('  ').convert(scenarios)};\n',
  );
  stdout.writeln(
    'Wrote ${scenarios.length} scenarios to ${jsonFile.path} and ${dartFile.path}',
  );
}

Map<String, Object?> _scenario(_ScenarioSeed seed, int sequence) {
  final event1Start = _at(seed.event1At);
  final event2Start = _at(seed.event2At);
  final todoDue = _at(seed.todoDue);
  final tags = [seed.category, seed.tag];

  return {
    'id': 'large_scenario_${sequence.toString().padLeft(3, '0')}',
    'key': seed.id,
    'name': seed.name,
    'category': seed.category,
    'summary': seed.background,
    'messages': [
      {
        'text':
            '我正在准备${seed.name}。${seed.background} '
            '先安排${seed.event1Title}，时间${_friendly(event1Start)}；'
            '${seed.todoTitle}最晚在${_friendly(todoDue)}前完成；'
            '再记录${seed.knowledge1Title}。',
        'assistant': '已整理${seed.name}的第一批事项和知识。',
        'calls': [
          _matter(seed, tags),
          _event(seed.event1Title, seed.background, event1Start, tags),
          _todo(seed.todoTitle, todoDue, tags),
          _knowledge(seed.knowledge1Title, seed.knowledge1Body, tags),
        ],
      },
      {
        'text':
            '补充${seed.name}的第二阶段。${seed.details} '
            '${seed.event2Title}安排在${_friendly(event2Start)}，'
            '同时整理${seed.knowledge2Title}。',
        'assistant': '已补齐${seed.name}的第二批事项和知识。',
        'calls': [
          _event(seed.event2Title, seed.details, event2Start, tags),
          _knowledge(seed.knowledge2Title, seed.knowledge2Body, tags),
        ],
      },
    ],
  };
}

Map<String, Object?> _matter(_ScenarioSeed seed, List<String> tags) {
  return {
    'type': 'matter',
    'title': seed.name,
    'body': seed.background,
    'confidence': 0.96,
    'sensitive': false,
    'tags': tags,
    'expect': 'created',
  };
}

Map<String, Object?> _event(
  String title,
  String body,
  DateTime start,
  List<String> tags,
) {
  return {
    'type': 'event',
    'title': title,
    'body': body,
    'confidence': 0.95,
    'sensitive': false,
    'tags': tags,
    'start': start.toIso8601String(),
    'end': start.add(const Duration(hours: 2)).toIso8601String(),
    'all_day': false,
    'expect': 'created',
  };
}

Map<String, Object?> _todo(String title, DateTime due, List<String> tags) {
  return {
    'type': 'todo',
    'title': title,
    'body': '在截止时间前完成：$title',
    'confidence': 0.94,
    'sensitive': false,
    'tags': tags,
    'due': due.toIso8601String(),
    'expect': 'created',
  };
}

Map<String, Object?> _knowledge(String title, String body, List<String> tags) {
  return {
    'type': 'knowledge',
    'title': title,
    'body': body,
    'confidence': 0.93,
    'sensitive': false,
    'tags': tags,
    'expect': 'created',
  };
}

DateTime _at(String value) => DateTime.parse(value);

String _fixtureAt(int day, int hour) {
  final dayText = day.toString().padLeft(2, '0');
  final hourText = hour.toString().padLeft(2, '0');
  return '2026-11-${dayText}T${hourText}:00:00+08:00';
}

String _friendly(DateTime value) {
  final local = value.toUtc().add(const Duration(hours: 8));
  final hour = local.hour;
  final period = hour < 6
      ? '凌晨'
      : hour < 12
      ? '上午'
      : hour < 18
      ? '下午'
      : '晚上';
  final displayHour = hour > 12 ? hour - 12 : hour;
  final minute = local.minute == 0
      ? ''
      : '${local.minute.toString().padLeft(2, '0')}分';
  return '${local.month}月${local.day}日$period$displayHour点$minute';
}

class _ScenarioSeed {
  const _ScenarioSeed({
    required this.id,
    required this.name,
    required this.category,
    required this.tag,
    required this.background,
    required this.details,
    required this.event1Title,
    required this.event1At,
    required this.event2Title,
    required this.event2At,
    required this.todoTitle,
    required this.todoDue,
    required this.knowledge1Title,
    required this.knowledge1Body,
    required this.knowledge2Title,
    required this.knowledge2Body,
  });

  final String id;
  final String name;
  final String category;
  final String tag;
  final String background;
  final String details;
  final String event1Title;
  final String event1At;
  final String event2Title;
  final String event2At;
  final String todoTitle;
  final String todoDue;
  final String knowledge1Title;
  final String knowledge1Body;
  final String knowledge2Title;
  final String knowledge2Body;
}
